- platform: template
  sensors:
    sun_rise:
      friendly_name: 'Next Sunrise'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(" %I:%M %p") | replace(" 0", "") }}'
      icon_template: mdi:weather-sunset-up
    sun_set:
      friendly_name: 'Next Sunset'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(" %I:%M %p") | replace(" 0", "") }}'
      icon_template: mdi:weather-sunset-down

